# SPDX-License-Identifier: GPL-2.0+
#
# /cpu bindings
#
# Copyright 2018 Google LLC
#

from kschema import NodeCpu, NodeCpus
from kschema import PropClocks, PropPhandle, PropReg, PropString, PropSupply

enable_methods = [
    'actions,s500-smp',
    'allwinner,sun6i-a31',
    'allwinner,sun8i-a23',
    'allwinner,sun9i-a80-smp',
    'amlogic,meson8-smp',
    'amlogic,meson8b-smp',
    'arm,realview-smp',
    'brcm,bcm11351-cpu-method',
    'brcm,bcm23550',
    'brcm,bcm2836-smp',
    'brcm,bcm-nsp-smp',
    'brcm,brahma-b15',
    'marvell,armada-375-smp',
    'marvell,armada-380-smp',
    'marvell,armada-390-smp',
    'marvell,armada-xp-smp',
    'marvell,98dx3236-smp',
    'mediatek,mt6589-smp',
    'mediatek,mt81xx-tz-smp',
    'qcom,gcc-msm8660',
    'qcom,kpss-acc-v1',
    'qcom,kpss-acc-v2',
    'renesas,apmu',
    'renesas,r9a06g032-smp',
    'rockchip,rk3036-smp',
    'rockchip,rk3066-smp',
    'ste,dbx500-smp',
]

schema = [
    NodeCpus(),
    NodeCpu(['arm,arm710t',
              'arm,arm720t',
              'arm,arm740t',
              'arm,arm7ej-s',
              'arm,arm7tdmi',
              'arm,arm7tdmi-s',
              'arm,arm9es',
              'arm,arm9ej-s',
              'arm,arm920t',
              'arm,arm922t',
              'arm,arm925',
              'arm,arm926e-s',
              'arm,arm926ej-s',
              'arm,arm940t',
              'arm,arm946e-s',
              'arm,arm966e-s',
              'arm,arm968e-s',
              'arm,arm9tdmi',
              'arm,arm1020e',
              'arm,arm1020t',
              'arm,arm1022e',
              'arm,arm1026ej-s',
              'arm,arm1136j-s',
              'arm,arm1136jf-s',
              'arm,arm1156t2-s',
              'arm,arm1156t2f-s',
              'arm,arm1176jzf',
              'arm,arm1176jz-s',
              'arm,arm1176jzf-s',
              'arm,arm11mpcore',
              'arm,armv8', # Only for s/w models
              'arm,cortex-a5',
              'arm,cortex-a7',
              'arm,cortex-a8',
              'arm,cortex-a9',
              'arm,cortex-a12',
              'arm,cortex-a15',
              'arm,cortex-a17',
              'arm,cortex-a53',
              'arm,cortex-a57',
              'arm,cortex-a72',
              'arm,cortex-a73',
              'arm,cortex-m0',
              'arm,cortex-m0+',
              'arm,cortex-m1',
              'arm,cortex-m3',
              'arm,cortex-m4',
              'arm,cortex-r4',
              'arm,cortex-r5',
              'arm,cortex-r7',
              'brcm,brahma-b15',
              'brcm,brahma-b53',
              'brcm,vulcan',
              'cavium,thunder',
              'cavium,thunder2',
              'faraday,fa526',
              'intel,sa110',
              'intel,sa1100',
              'marvell,feroceon',
              'marvell,mohawk',
              'marvell,pj4a',
              'marvell,pj4b',
              'marvell,sheeva-v5',
              'marvell,sheeva-v7',
              'nvidia,tegra132-denver',
              'nvidia,tegra186-denver',
              'nvidia,tegra194-carmel',
              'qcom,krait',
              'qcom,kryo',
              'qcom,kryo385',
              'qcom,scorpion'], [
        PropString('device_type', True, ''),
        PropReg(),
        PropClocks(),
        PropString('enable-method', True, 'psci|spin-table',
                   {'#arch': 'armv8'}),
        PropString('enable-method', False, '|'.join(enable_methods),
                   {'#arch': '!armv8'}),
        PropPhandle('rockchip,pmu', 'rockchip,rk3288-pmu',
                    cond_props={'enable-method': 'rockchip,rk3066-smp'}),
        PropSupply('cpu'),
    ]),
]
